spring:
  application:
    name: BidBridge Simulator
  profiles:
    default: local
  codec:
    max-in-memory-size: 1MB
server:
  netty:
    response-timeout: 5s
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
