spring:
  application:
    name: BidBridge Simulator
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

simulator:
  enabled: true
  bidProbability: 0.5
  fixedPrice: 100
  currency: "RON"
  admTemplate: "<vast/>"
  responseDelayMs: 0
