server:
  port: 8081
dsps:
  file: "s3://your-bucket/dsps.yml"
  pollIntervalMs: 10000
  awsRegion: "eu-north-1"
simulator:
  auth:
    enabled: true
    bidApiKey: "${BID_API_KEY:}"
    adminApiToken: "${ADMIN_API_TOKEN:}"
