spring:
  application:
    name: BidBridge Engine
  codec:
    max-in-memory-size: 2MB
server:
  port: 8080
management:
  info:
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    ro.dede.bidbridge.engine: INFO
  pattern:
    console: "%X{correlationId:-system} - %d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level %logger{36} - %msg%n"

adapters:
  configs:
    simulator:
      enabled: true
      timeoutMs: 80
      bidProbability: 1.0
      fixedPrice: 0.5
      admTemplate: "<vast/>"
    simulatorHttp:
      enabled: true
      endpoint: "http://localhost:8081/openrtb2/bid"
      timeoutMs: 60000

rules:
  allowInventory: [ SITE ]
  minBidfloor: 0.5
  allowAdapters: [ simulator, simulatorHttp ]

bid:
  globalTimeoutMs: 0
