spring:
  application:
    name: BidBridge Engine
  codec:
    max-in-memory-size: 2MB
server:
  port: 8080
management:
  info:
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    ro.dede.bidbridge.engine: INFO

adapters:
  simulator:
    enabled: true
    timeoutMs: 80
    bidProbability: 1.0
    fixedPrice: 1.5
    admTemplate: "<vast/>"
